version: '3.5'

services:
  nginx:
      image: nginx:latest
      ports:
          - 80:80
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - .:/var/www/html:cached
      depends_on:
          - php

  php:
      build:
          context: .
          dockerfile: docker/php/Dockerfile
      expose:
          - 9000
      volumes:
          - .:/var/www/html:cached
      environment:
          XDEBUG_CONFIG: remote_host=172.17.0.1
          PHP_IDE_CONFIG: serverName=0.0.0.0
  node:
      build:
          context: .
          dockerfile: docker/node/Dockerfile
      expose:
          - 3000
      ports:
          - "3000:3000"
      volumes:
          - .:/var/www/html:cached

  redis:
      image: redis
      ports:
          - 6379:6379
